flat_first.Rmd:
  path: dev/flat_first.Rmd
  state: active
  R:
  - R/bagginsclass.R
  - R/entclass.R
  - R/exprentclass.R
  - R/methylentclass.R
  - R/moriaclass.R
  - R/samwiseclass.R
  tests:
  - tests/testthat/test-bagginsclass.R
  - tests/testthat/test-samwiseclass.R
  - tests/testthat/test-moriaclass.R
  - tests/testthat/test-entclass.R
  - tests/testthat/test-exprentclass.R
  - tests/testthat/test-methylentclass.R
  vignettes: vignettes/get-started.Rmd
  inflate:
    flat_file: dev/flat_first.Rmd
    vignette_name: Get started
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
