# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' promoter with gene annotation
#' @name promoter_probe
#' @description A database of promoter island with gene annotation information.
#' @format A data frame with promoter island with gene annotation.

