# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand

#' MethylEntClass
#' 
#' MethylEntClass : The world is changing. I feel it in the water. I feel it in the earth. I smell it in the air. Much that once was is now lost, for none now live who remember it.
#' 
#' @return R6_object
#' 
#' @export
#' @examples
#' MethylEnt <- MethylEntClass$new()
MethylEntClass <- R6::R6Class(
  "MethylEntClass/MethySet",
  inherit = EntClass,
  public = list(
    #' @method Plot hetmap
    #' @param p_thred default as 0.05
    #' @param logFC_thred default as 1
    #' @param topn default as 30
    #' @return fig
    Plot_hetmap = function(p_thred = 0.05,logFC_thred = 1 ,topn = 30){
      library(pheatmap)
      group_sample <- self$pdata %>% dplyr::arrange(.[[self$group_index]])
      group_order <- group_sample[[self$sample_index]]
      expr_normal_df2 <- self$array %>% 
        dplyr::select(all_of(group_order))
      rownames(expr_normal_df2) <- self$array[,1]
      group_list <- factor(group_sample[[self$group_index]])
      deg <- self$DA_result %>% 
        dplyr::mutate(change = ifelse(adj.P.Val < p_thred & abs(logFC) > logFC_thred,
                                      ifelse(logFC > logFC_thred ,'UP','DOWN'),'NOT')) %>% 
        dplyr::filter(change != "NOT") %>% 
        dplyr::arrange('adj.P.Val')
      display_gene = rownames(deg)
      cg=c(names(head(sort(display_gene),topn)),names(tail(sort(display_gene),topn)))
      n=t(scale(t(expr_normal_df2[cg,])))
      n[n>2]=2
      n[n< -2]= -2
      n[1:4,1:4]
      ac=data.frame(group_list=group_list)
      rownames(ac)=colnames(n)
      p <- pheatmap(n,show_colnames =F,show_rownames = T,annotation_col=ac)
      library(ggplotify)
      as.ggplot(p) + theme(plot.margin = margin(l = 5, r = 10))
    },
    #' @method Plot vocalno
    #' @param style_id default as 1,2
    #' @param logFC_thred default as 1
    #' @return fig
    Plot_vocalno = function(style_id,logFC_thred){
      need_deg=data.frame(symbols=rownames(self$DMP_table), logFC=self$DMP_table[["logFC"]], p=self$DMP_table[["adj.P.Val"]])
      AnnoProbe::deg_volcano(need_deg,style_id,logFC_thred = logFC_thred)
    },
    #' @method matrix annotate
    #' @param type chr promoter or cpg
    #' @param df_object the converted data
    #' @return data.frame
    matrix_annotate = function(df_object = c("DA_result","array"),type = "cpg"){
      
      rrbs_annote4DMP <- function(DMP_df,type = "cpg",
                                  cpg_bedgraph){
        unannote_list <- rownames(DMP_df)
        if (type == "promoter"){
           g_id <- cpg_bedgraph
           g_id <- g_id %>%
             dplyr::select(-gene_id) %>%
             filter(idx %in% unannote_list)
        } else {
          g_id <- data.table::fread(cpg_bedgraph) 
          for (i in 1:nrow(g_id)){
            if (is.na(g_id$symbol[i]) | is.null(g_id$symbol[i])){
              g_id$symbol[i] <- g_id$idx[i]
            }else {
              next
            }
          }
          g_id <- g_id %>% 
            dplyr::select(-gene_id) %>%
            filter(idx %in% unannote_list)
        }
        DMP_df_colnames <- c(colnames(g_id),colnames(DMP_df))
        row_df <- rownames(DMP_df)
        DMP_df <- DMP_df %>%  
          mutate(idx = row_df) %>% 
          filter(idx %in% g_id$idx) %>% 
          left_join(g_id,by = "idx") %>% 
          dplyr::select(all_of(c("idx",DMP_df_colnames) ))
        return(DMP_df)
      }
       if (type == "cpg"){
         referdata <- cpg_probe
         } else {
           referdata <- promoter_probe
         }
      if (df_object == "DA_result"){
        convertdata <- self$DA_result
      }else {
        convertdata <- self$array
      }
      
      df <- rrbs_annote4DMP(DMP_df = convertdata ,type = type,
                                  cpg_bedgraph = referdata)
      
      return(df)
    },
    
    #' @method gene enrich
    #' @param pathwaydb chr go or kegg
    #' @param genedb data.frame the genedb data
    #' @return list
    gene_enrich = function(pathwaydb,genedb = Entrez_Gene_Id_db){
      enrichment_in_action <- function(df,types){
        if (types == "go"){
          result <- clusterProfiler::enrichGO(df, 'org.Hs.eg.db', ont="BP", pvalueCutoff=0.01)
        } else {
          result <- clusterProfiler::enrichKEGG(df, organism = "hsa",
                                                keyType = "kegg",
                                                pvalueCutoff = 0.01,
                                                pAdjustMethod = "BH",
                                                minGSSize = 10,
                                                maxGSSize = 500,
                                                qvalueCutoff = 0.2,
                                                use_internal_data = FALSE)
        }
      }
      gene2entrez <- function(genelist,db = genedb){
        # need further tidy evaluation
        db %>% 
          dplyr::filter(SYMBOL %in% genelist) %>% 
          dplyr::select(ENTREZID) %>% 
          as.vector() %>% 
          unlist()
      }
      enrichlist <- list()
      for (changeType in c("UP","DOWN")){
        DEG <- self$DA_result %>% 
        dplyr::mutate(change = ifelse(adj.P.Val < p_thred & abs(logFC) > logFC_thred,
                                      ifelse(logFC > logFC_thred ,'UP','DOWN'),'NOT')) %>% 
        dplyr::filter(change == changeType) 
        
        DEG <- DEG$symbol %>%
        gene2entrez(genedb) %>% 
        as.vector() %>% unique() %>% 
        enrichment_in_action(types = pathwaydb)
      
      Go_result <- DEG@result %>% 
        tidyr::separate(col=GeneRatio,into = c("GR1", "GR2"), sep = "/") %>% 
        tidyr::separate(col=BgRatio, into = c("BR1", "BR2"), sep = "/") %>% 
        dplyr::mutate(enrichment_factor = (as.numeric(GR1)/as.numeric(GR2))/(as.numeric(BR1)/as.numeric(BR2))) %>% 
        dplyr::mutate(generatio = (as.numeric(GR1)/as.numeric(GR2))) %>% 
        dplyr::arrange(-enrichment_factor)
      enrichlist[[changeType]] <- Go_result 
      }
     return(enrichlist)
    },
    #' @method convert Beta2M_value
    #' @return data.frame
    Mvalue_transform = function( ){
      matrixdf <- self$array[,-1] %>% as.matrix()
      result <- matrixdf / (1 - matrixdf)
      df <- as.data.frame(result) %>% mutate(idx = self$probel) %>% relocate(idx)
      return(df)
    }
  )
)
